import { Link } from 'react-router-dom';
import Page, { MobileOrderBar } from '@/components/layout/Page';
import { COMBOS, getProduct } from '@/lib/catalog';
import { useCart } from '@/context/CartContext';
import { money, pad } from '@/lib/format';
import { SHOP } from '@/lib/shop';
import Icon from '@/components/ui/Icon';
import { ActionButton, Reveal } from '@/components/ui/primitives';
import { Glow } from '@/components/ui/Atmosphere';
import ProductArt from '@/components/product/ProductArt';

/* ================================================================== */
/* Palette                                                             */
/* ================================================================== */

/**
 * One rule across the site: a #32080B surface carries white type, a light
 * surface carries #32080B type. Yellow is a fill, never text on cream —
 * it only appears as a background with black on top, or as a hairline.
 */
const BROWN = '#32080B';
const CREAM = '#FFF8EE';
const YELLOW = '#FFC93C';
const BLACK = '#0A0506';

/**
 * Combos are not a separate product line — each one is a selection of real
 * rows from the same price list, generated by rule in scripts/build-catalog.
 * The page says so plainly, because a customer who spots a familiar line and
 * checks the arithmetic should find it holds up.
 */
export default function Combos() {
  const { addMany } = useCart();

  return (
    <Page
      title="Combo boxes — pre-built Diwali selections | Veyila Crackers"
      description="Four ready-made Diwali boxes built from the Veyila Crackers price list: Kids Safe Box, Family Evening, Full Street and Sky Premium. Add all lines to your sheet in one press."
      canonical="/combos"
      trail={[{ label: 'Combo boxes' }]}
      eyebrow={<span className="text-[#32080B]/70">{COMBOS.length} selections</span>}
      heading={<span className="text-[#32080B]">Boxes somebody already thought about</span>}
      lead={
        <span className="text-[#32080B]/65">
          Each box is a set of real lines from the price list, picked to cover an evening without leaving gaps or
          doubling up. Add the whole thing, then take out anything you don't want.
        </span>
      }
    >
      <div className="shell space-y-8 pb-24">
        {COMBOS.map((combo, index) => (
          <Reveal key={combo.id} delay={index * 0.06}>
            <article
              id={combo.slug}
              className="relative scroll-mt-32 overflow-hidden rounded-2xl border border-white/10 bg-[#32080B] p-7 lg:p-10"
            >
              <Glow className="-right-24 -top-24" color="rgba(255,201,60,.10)" size={380} />

              <div className="grid gap-10 lg:grid-cols-[1.15fr_1fr] lg:gap-16">
                <div>
                  <div className="mb-5 flex items-center gap-3">
                    <span className="num text-2xs text-white/40">{pad(index + 1)}</span>
                    <span className="h-px w-8 bg-[#FFC93C]/60" />
                    <span className="eyebrow text-[#FFC93C]">{combo.tagline}</span>
                  </div>

                  <h2 className="text-headline text-white">{combo.name}</h2>
                  <p className="mt-5 max-w-xl text-pretty leading-relaxed text-white/65">{combo.blurb}</p>

                  <dl className="mt-8 flex flex-wrap gap-x-10 gap-y-5 border-y border-white/15 py-6">
                    {[
                      ['Lines inside', combo.itemCount],
                      ['List price', money(combo.mrp)],
                      ['Box price', money(combo.price)],
                      ['You save', money(combo.mrp - combo.price)],
                    ].map(([label, value]) => (
                      <div key={label}>
                        <dt className="eyebrow mb-1.5 text-white/50">{label}</dt>
                        <dd className="num text-lg font-semibold text-white">{value}</dd>
                      </div>
                    ))}
                  </dl>

                  <div className="mt-7 flex flex-wrap items-center gap-3">
                    <button
                      type="button"
                      onClick={() => addMany(combo.items)}
                      className="flex items-center gap-2 rounded-pill bg-[#FFC93C] px-5 py-2.5 font-mono text-2xs font-bold uppercase tracking-[0.16em] text-[#0A0506] transition-colors hover:bg-white"
                    >
                      Add all {combo.itemCount} lines
                      <Icon name="plus" size={15} />
                    </button>
                    <span className="num rounded-pill border border-[#FFC93C]/50 px-3 py-1.5 text-[0.62rem] uppercase tracking-widest text-[#FFC93C]">
                      {combo.discount}% off list
                    </span>
                    <p className="text-xs text-white/45">
                      Includes an extra {combo.bundleDiscount}% for taking the box as picked.
                    </p>
                  </div>
                </div>

                {/* contents */}
                <div>
                  <p className="eyebrow mb-4 text-[#FFC93C]">What's in it</p>
                  <ul className="divide-y divide-white/12 border-y border-white/15">
                    {combo.items.map((item) => {
                      const product = getProduct(item.slug);
                      if (!product) return null;
                      return (
                        <li key={item.slug} className="flex items-center gap-3 py-2.5">
                          <span className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-md bg-[#0A0506]">
                            <ProductArt
                              art={product.art}
                              hue={product.hue}
                              seed={product.slug}
                              className="h-full w-full"
                            />
                          </span>
                          <span className="min-w-0 flex-1">
                            <Link
                              to={`/product/${product.slug}`}
                              className="block truncate text-sm text-white transition-colors hover:text-[#FFC93C]"
                            >
                              {product.name}
                            </Link>
                            <span className="block truncate text-2xs text-white/45">{product.category}</span>
                          </span>
                          <span className="num shrink-0 text-sm text-white/70">{money(product.price)}</span>
                        </li>
                      );
                    })}
                  </ul>
                  <p className="num mt-3 flex justify-between text-sm">
                    <span className="text-white/50">Lines added up</span>
                    <span className="text-white/80">{money(combo.subtotal)}</span>
                  </p>
                  <p className="num mt-1 flex justify-between text-sm">
                    <span className="text-white/50">Box discount</span>
                    <span className="text-[#FFC93C]">− {money(combo.subtotal - combo.price)}</span>
                  </p>
                </div>
              </div>
            </article>
          </Reveal>
        ))}

        <Reveal className="flex flex-col items-start gap-5 rounded-2xl border border-white/10 bg-[#32080B] p-8 sm:flex-row sm:items-center sm:justify-between lg:p-10">
          <div className="max-w-xl">
            <h2 className="text-title mb-2 text-white">Want a box built round a budget?</h2>
            <p className="text-pretty leading-relaxed text-white/65">
              Tell us the figure and who's burning them — small children, a terrace, a whole street — and we'll put a
              sheet together and send it back for you to edit.
            </p>
          </div>
          <a
            href={`tel:+91${SHOP.phone}`}
            className="flex shrink-0 items-center gap-2 rounded-pill bg-[#FFC93C] px-5 py-2.5 font-mono text-2xs font-bold uppercase tracking-[0.16em] text-[#0A0506] transition-colors hover:bg-white"
          >
            <Icon name="phone" size={15} />
            {SHOP.phoneDisplay}
          </a>
        </Reveal>
      </div>

      <MobileOrderBar />
    </Page>
  );
}